package management.views.histories.output;

import management.controllers.histories.OutputHistoryController;

public class OutputHistoryJFrame extends javax.swing.JFrame {

    private final OutputHistoryController outputController = new OutputHistoryController();
    
    public OutputHistoryJFrame() {
        initComponents();
        
        outputController.showAllOutputData(outputHistoryTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputHistoryTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        viewDetailButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(0, 730));
        setPreferredSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        allPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        outputHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(outputHistoryTable);

        allPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 600, 360));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\wk\\Downloads\\icons8-update-30.png")); // NOI18N
        jButton1.setText("Xác nhận");
        allPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, 120, 40));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\wk\\Downloads\\icons8-cancel-30.png")); // NOI18N
        jButton2.setText("Hủy");
        allPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, 120, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\wk\\Downloads\\icons8-delete-24.png")); // NOI18N
        jButton3.setText("Xóa");
        allPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 150, 50));

        refreshButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        refreshButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\wk\\Downloads\\icons8-reset-24.png")); // NOI18N
        refreshButton.setText("Làm mới");
        refreshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshButtonMouseClicked(evt);
            }
        });
        allPanel.add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 150, 50));

        addButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        addButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\wk\\Downloads\\icons8-add-properties-24.png")); // NOI18N
        addButton.setText("Thêm");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });
        allPanel.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, 50));

        viewDetailButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        viewDetailButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\wk\\Downloads\\icons8-view-details-26.png")); // NOI18N
        viewDetailButton.setText("Xem chi tiết");
        allPanel.add(viewDetailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Chức Năng ");
        allPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel3.setText("LỊCH SỬ XUẤT KHO");
        allPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 370, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\wk\\Downloads\\Lịch sử xuất kho.png")); // NOI18N
        allPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 700));

        getContentPane().add(allPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshButtonMouseClicked
        outputController.showAllOutputData(outputHistoryTable);
    }//GEN-LAST:event_refreshButtonMouseClicked

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        AddOutputHistoryJFrame frame = new AddOutputHistoryJFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_addButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutputHistoryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutputHistoryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutputHistoryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutputHistoryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutputHistoryJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel allPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable outputHistoryTable;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton viewDetailButton;
    // End of variables declaration//GEN-END:variables
}
