package management.views;

import management.controllers.main.MainController;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

import java.util.concurrent.TimeUnit;
import org.eclipse.paho.client.mqttv3.MqttException;

import java.awt.Dimension;

public class MainJFrame extends javax.swing.JFrame {
    private int xMouse;
    private int yMouse;
    boolean showDashboard = false;

    private final MainController mainController = new MainController();
    
    public MainJFrame() throws MqttException{
        initComponents();
        dashboard.setVisible(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        mainController.showAllInfo(storageInfo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        minmaxclose = new javax.swing.JPanel();
        minimize = new javax.swing.JPanel();
        minButton = new javax.swing.JLabel();
        maximize = new javax.swing.JPanel();
        maxButton = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        closeButton = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        workplace = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        storageInfo = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        header.setBackground(new java.awt.Color(0, 153, 0));
        header.setPreferredSize(new java.awt.Dimension(800, 50));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new java.awt.BorderLayout());

        minmaxclose.setPreferredSize(new java.awt.Dimension(150, 50));
        minmaxclose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setBackground(new java.awt.Color(0, 102, 51));
        minimize.setPreferredSize(new java.awt.Dimension(50, 50));
        minimize.setLayout(new java.awt.BorderLayout());

        minButton.setForeground(new java.awt.Color(255, 255, 255));
        minButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minButton.setText("______");
        minButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minButtonMouseClicked(evt);
            }
        });
        minimize.add(minButton, java.awt.BorderLayout.CENTER);

        minmaxclose.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        maximize.setBackground(new java.awt.Color(42, 105, 33));
        maximize.setPreferredSize(new java.awt.Dimension(50, 50));
        maximize.setLayout(new java.awt.BorderLayout());

        maxButton.setBackground(new java.awt.Color(42, 105, 33));
        maxButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/full_screen_32px.png"))); // NOI18N
        maxButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        maxButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxButtonMouseClicked(evt);
            }
        });
        maximize.add(maxButton, java.awt.BorderLayout.CENTER);

        minmaxclose.add(maximize, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, -1));

        close.setBackground(new java.awt.Color(42, 105, 33));
        close.setPreferredSize(new java.awt.Dimension(50, 50));
        close.setLayout(new java.awt.BorderLayout());

        closeButton.setBackground(new java.awt.Color(42, 105, 33));
        closeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete_32px.png"))); // NOI18N
        closeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        close.add(closeButton, java.awt.BorderLayout.CENTER);

        minmaxclose.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, -1));

        header.add(minmaxclose, java.awt.BorderLayout.LINE_END);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        background.setBackground(new java.awt.Color(204, 255, 204));
        background.setPreferredSize(new java.awt.Dimension(1280, 720));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(0, 153, 0));
        sidebar.setPreferredSize(new java.awt.Dimension(50, 50));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        background.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 780));

        dashboard.setBackground(new java.awt.Color(0, 102, 51));
        dashboard.setPreferredSize(new java.awt.Dimension(400, 710));
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(350, 50));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Danh mục");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 40));

        dashboard.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 40));

        background.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 220, 780));

        storageInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(storageInfo);

        workplace.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout workplaceLayout = new javax.swing.GroupLayout(workplace);
        workplace.setLayout(workplaceLayout);
        workplaceLayout.setHorizontalGroup(
            workplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workplaceLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        workplaceLayout.setVerticalGroup(
            workplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workplaceLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                .addContainerGap())
        );

        background.add(workplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1030, 770));

        getContentPane().add(background, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        //Nút tắt 
        dispose();
    }//GEN-LAST:event_closeButtonMouseClicked

    
    private void maxButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxButtonMouseClicked
        if (this.getExtendedState() != MainJFrame.MAXIMIZED_BOTH){
            this.setExtendedState(MainJFrame.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(MainJFrame.NORMAL);
        }
    }//GEN-LAST:event_maxButtonMouseClicked

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void changeImage(JLabel button, String srcImage){
        ImageIcon img = new ImageIcon(getClass().getResource(srcImage));
        button.setIcon(img);
    }
    
   
    
    
    private void minButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minButtonMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minButtonMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    MainJFrame mainFrame = new MainJFrame();
                    mainFrame.setVisible(true);
                }
                catch (MqttException e){
                    System.out.println("Mqtt Error in main frame");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closeButton;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maxButton;
    private javax.swing.JPanel maximize;
    private javax.swing.JLabel minButton;
    private javax.swing.JPanel minimize;
    private javax.swing.JPanel minmaxclose;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTable storageInfo;
    private javax.swing.JLayeredPane workplace;
    // End of variables declaration//GEN-END:variables
}
