package management.views.categories.device;

import javax.swing.JOptionPane;
import management.controllers.categories.DeviceController;

public class UpdateIDDeviceJDialog extends javax.swing.JDialog {
    private boolean isView = false;
    private boolean firstPress = true;
    
    private final DeviceController deviceController = new DeviceController();
    
    public UpdateIDDeviceJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        lblDeviceNum.setVisible(false);
        tfDeviceNum.setVisible(false);
    }
    
    public UpdateIDDeviceJDialog(java.awt.Frame parent, boolean modal, String _deviceId) {
        super(parent, modal);
        initComponents();
        
        lblDeviceNum.setVisible(false);
        tfDeviceNum.setVisible(false);
        tfDeviceId.setText(_deviceId);
    }
    
    public UpdateIDDeviceJDialog(java.awt.Frame parent, boolean modal, String _deviceId, int _deviceNum) {
        super(parent, modal);
        initComponents();
        
        viewInit(_deviceId, _deviceNum);
        isView = true;
    }
    
    private void viewInit(String _deviceId, int _deviceNum){
        tfDeviceId.setText(_deviceId);
        tfDeviceNum.setText(String.valueOf(_deviceNum));
        
        tfDeviceId.setEditable(false);
        tfDeviceNum.setEditable(false);
        tfStorageId.setEditable(false);
        tfDeviceNote.setEditable(false);
        deviceController.showSingleIDDevice(tfDeviceId, tfDeviceNum, tfStorageId, tfDeviceNote);
        
        btnConfirm.setText("Sửa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        tfDeviceNote = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfStorageId = new javax.swing.JTextField();
        tfDeviceId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfDeviceNum = new javax.swing.JTextField();
        lblDeviceNum = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(680, 750));
        setMinimumSize(new java.awt.Dimension(670, 750));
        setPreferredSize(new java.awt.Dimension(685, 730));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfirm.setBackground(new java.awt.Color(204, 204, 204));
        btnConfirm.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/thêm.png"))); // NOI18N
        btnConfirm.setText("Xác nhận");
        btnConfirm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmMouseClicked(evt);
            }
        });
        getContentPane().add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 650, 150, 50));

        btnCancel.setBackground(new java.awt.Color(204, 204, 204));
        btnCancel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/thoát.png"))); // NOI18N
        btnCancel.setText("Hủy");
        btnCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 650, 150, 50));
        getContentPane().add(tfDeviceNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 370, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setText("Ghi chú");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 526, -1, 70));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("Mã kho");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 416, -1, 70));
        getContentPane().add(tfStorageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 370, 50));
        getContentPane().add(tfDeviceId, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 370, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Mã thiết bị");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 226, -1, 70));
        getContentPane().add(tfDeviceNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 370, 50));

        lblDeviceNum.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblDeviceNum.setText("Số thứ tự");
        getContentPane().add(lblDeviceNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 326, -1, 60));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel5.setText("CHI TIẾT MÃ THIẾT BỊ ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeviceDetail/AddTagForDeviceJFrame.png"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(680, 730));
        jLabel4.setMinimumSize(new java.awt.Dimension(680, 730));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseClicked
        if (isView){
            if (firstPress){ 
                firstPress = false;
                
                btnConfirm.setText("Sửa");     
                
                tfStorageId.setEditable(true);
                tfDeviceNote.setEditable(true);                  
            }
            else{
                boolean success = deviceController.updateIdDevice(tfDeviceId, tfDeviceNum, tfStorageId, tfDeviceNote);
                if (success){
                    JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
                    dispose();
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "Sửa không thành công");
            }
        } else {
            boolean success = deviceController.addIdDevice(tfDeviceId, tfStorageId, tfDeviceNote);
            if (success){
                JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                
                tfStorageId.setText("");
                tfDeviceNote.setText("");
                
                tfStorageId.requestFocus();
            }
        }
    }//GEN-LAST:event_btnConfirmMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateIDDeviceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateIDDeviceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateIDDeviceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateIDDeviceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateIDDeviceJDialog dialog = new UpdateIDDeviceJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblDeviceNum;
    private javax.swing.JTextField tfDeviceId;
    private javax.swing.JTextField tfDeviceNote;
    private javax.swing.JTextField tfDeviceNum;
    private javax.swing.JTextField tfStorageId;
    // End of variables declaration//GEN-END:variables
}
